/*
 * Unitex
 *
 * Copyright (C) 2001-2018 Université Paris-Est Marne-la-Vallée <unitex@univ-mlv.fr>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 *
 */
package leximir;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
 *
 * @author Anas Ait cheikh
 */
public class CsvOpener extends javax.swing.JInternalFrame {

    private String csvfile;

    public CsvOpener(String csvfile) {
        super("Statistic on table", true, true, true, true);
        this.csvfile = csvfile;
        initComponents();

    }

    private Vector<String> header() {
        try {
            BufferedReader fichier_source = new BufferedReader(new FileReader(csvfile));
            String chaine;
            if ((chaine = fichier_source.readLine()) != null) {
                return new Vector<String>(Arrays.asList(chaine.split(";")));
            }
        } catch (Exception e) {
            System.out.println("Le fichier est introuvable !");
        }
        return null;
    }

    private Vector<Vector> read() {
        Vector<Vector> tmp = new Vector<Vector>();
        try {
            BufferedReader fichier_source = new BufferedReader(new FileReader(csvfile));
            String chaine;
            int i = 1;
            while ((chaine = fichier_source.readLine()) != null) {
                if (i > 1) {
                    tmp.add(new Vector<String>(Arrays.asList(chaine.split(";"))));
                }
                i++;
            }
            fichier_source.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return tmp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                Vector<String> header = this.header();
        Vector<Vector> data = this.read();		
        JTable tableau = new JTable(data, header);
JScrollPane scrollpane=new JScrollPane(tableau,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
       JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    this.add(scrollpane);
    this.setVisible(true);
    this.setSize(450,400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
